### PR TITLE
Pre commit hook

### PR DESCRIPTION
**Pull request by htalat**
### Title
Pre commit hook
[#390] 

### What's Changed
Runs a test suite before making a commit which can be overridden 

### Technical Description
- used [husky](https://github.com/typicode/husky) to add a pre commit hook
- runs a test suite (a subset of the current `test.sh` file)
- can force a commit with `--no-verify` flag

### CODE REVIEW

**Comment by apoclyps** [comment]
Thank you @htalat for the PR; It looks good; can you rebase from master and I'll happily accept and merge it once CI is green

**Comment by htalat** [comment]
by `rebase from master` you mean syncing this branch?

**Comment by apoclyps** [comment]
yes; sync up this branch with master to pick up the latest changes and ensuring the history matches.

**Comment by htalat** [comment]
here you go!

**Pull request merged**
